version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.9"

python:
  install:
    - requirements: requirements.txt
    - requirements: docs/requirements.txt    

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

# Optionally build your docs in additional formats such as PDF
formats:
  - pdf
