version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.9"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs    

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

# Optionally build your docs in additional formats such as PDF
formats:
  - pdf
