# import the submodule objects
from . import input_parameters
from . import plots
from . import utils
from . import models
from . import chi2_fit
from . import bayes_fit
from . import phy_params
from . import variability
from . import archival_data.py
from .synthetic_photometry import synthetic_photometry
from .spectral_indices import spectral_indices

# try to get the version from _version.py (generated by setuptools_scm)
try:
	from ._version import __version__
except (ImportError, ModuleNotFoundError):  
	__version__ = "0.0.0+local"

# defines the explicit public API of the package
__all__ = [ 
    "input_parameters",
    "plots",
    "utils",
    "models",
    "chi2_fit",
    "bayes_fit",
    "phy_params",
    "synthetic_photometry",
    "spectral_indices",
    "variability"
]

# Print the version on import
public_version = __version__.split("+", 1)[0] # avoid long git hash
print(f'\n    SEDA v{public_version} package imported')
